name: ssm__pruner
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - conda-pack=0.8.0
  - einops=0.8.0
  - pip
  - pip:
      - accelerate==1.0.0rc1
      - bitsandbytes==0.42.0
      - datasets==2.21.0
      - evaluate==0.4.3
      - lm-eval==0.4.4
      - nltk==3.9.1
      - numpy==1.26.4
      - peft==0.13.0
      - sentencepiece==0.2.0
      - tokenizers==0.21.0
      - torch==2.4.0
      - tqdm==4.66.5
      - tqdm-multiprocess==0.0.11
      - transformers==4.48.1
      - trl==0.13.0
      - tzdata==2024.1
      - mamba-ssm