# Model arguments
model_name_or_path: llama3_0_875_mamba_sft/
torch_dtype: bfloat16

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 1.0
  HuggingFaceH4/orca_dpo_pairs: 1.0
  JunxiongWang/llama3-ultrafeedback-armorm: 1.0
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 64

# DPOTrainer arguments
bf16: true
beta: 0.01
do_eval: true
evaluation_strategy: steps
eval_steps: 2000
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 1
optim: adamw_torch
output_dir: llama3_0_875_mamba_dpo_ep1/
per_device_train_batch_size: 4
per_device_eval_batch_size: 8
push_to_hub: false
save_strategy: "steps"
save_steps: 1000
save_total_limit: 2
seed: 42
warmup_ratio: 0.1
report_to:
- wandb